### ISSUE TITLE
提示处理验证码，打开浏览器后无法验证

### ISSUE THREAD

**Issue by gaomugong** [Sniper970119/dianping_spider#22]
![image](https://user-images.githubusercontent.com/84143485/134505234-528982ae-17e1-4da3-a196-1ba8d9b7731e.png)

**Comment by Sniper970119** [comment]
清除浏览器缓存

**Comment by JackiyWu** [comment]
试了未解决。。。

**Comment by Sniper970119** [comment]
![图片](https://user-images.githubusercontent.com/30463691/136681422-789e4f30-670c-4597-9c80-f25be20a41f1.png)

**Comment by JackiyWu** [comment]
感谢大佬回复，我用的Chrome，试过了换成自己的Cookie，清空缓存，还是不行。这是还没开始爬就被封了吗。。。

**Comment by Sniper970119** [comment]
什么叫“试着换成自己的cookie”？必然要换啊，你是不是运行的有问题




------------------ 原始邮件 ------------------
发件人: coding_wu ***@***.***&gt;
发送时间: 2021年10月10日 14:36
收件人: Sniper970119/dianping_spider ***@***.***&gt;
抄送: Yu ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[Sniper970119/dianping_spider] 提示处理验证码，打开浏览器后无法验证 (#22)





 
感谢大佬回复，我用的Chrome，试过了换成自己的Cookie，清空缓存，还是不行。这是还没开始爬就被封了吗。。。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghuafeng** [comment]
也碰到了同样的问题，清理了浏览器缓存了，还是同样的问题
