### ISSUE TITLE
浏览器端油猴脚本

### ISSUE THREAD

**Issue by halsn** [Sniper970119/dianping_spider#28]
介于本人数次运行项目失败的经历，发现找一个靠谱便宜的代理服务十分困难，每次一运行就被ban了，所以我将作者的代码翻译成了油猴脚本，为不需要爬虫但是需要手动复制一些评论的人士使用，地址 https://greasyfork.org/scripts/435145

**Comment by Sniper970119** [comment]
感谢您的关注，麻烦提个PR，我帮您合并



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Evan ***@***.***&gt;
发送时间: 2021年11月16日 18:07
收件人: Sniper970119/dianping_spider ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Sniper970119/dianping_spider] 浏览器端油猴脚本 (Issue #28)





 
介于本人数次运行项目失败的经历，发现找一个靠谱便宜的代理服务十分困难，每次一运行就被ban了，所以我将作者的代码翻译成了油猴脚本，为不需要爬虫但是需要手动复制一些评论的人士使用，地址 https://greasyfork.org/scripts/435145
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
